
version: '3.8'
services:
  ai-world:
    build: .
    container_name: ai-world
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

